config/routes.rb
Rails.application.routes.draw do

  root 'kittens#index'

  resources :kittens

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.xml {render :xml => @kittens.to_xml}
      format.json {render :json => @kittens.to_json}
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten
      flash[:success] = "Successfully added kitten!"
    else
      render :new
      flash.now[:danger] = "Failed to add kitten"
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      redirect_to @kitten
      flash[:success] = "Successfully updated kitten"
    else
      render :edit
      flash.now[:danger] = "Failed to update kitten"
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.xml {render :xml => @kitten.to_xml}
      format.json {render :json => @kitten.to_json}
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to root_url
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :cuteness, :softness, :age)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :cuteness %>
  <%= f.number_field :cuteness %><br>

  <%= f.label :softness %>
  <%= f.number_field :softness %><br>

  <%= f.label :age %>
  <%= f.number_field :age %><br>

  <%= f.submit "Submit" %>
<% end %>

app/views/kittens/_kitten.html.erb
<h3><%= link_to kitten.name, kitten %></h3>
<ul>
  <li>Cuteness: <%= kitten.cuteness %></li>
  <li>Softness: <%= kitten.softness %></li>
  <li>Age: <%= kitten.age %></li>
</ul>
<%= form_for kitten, html: {method: :delete} do |f| %>
  <%= f.submit "Delete Kitten" %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit kitten</h1>
<%= render 'kittens/form' %>

app/views/kittens/index.html.erb
<h1>Kittens!</h1>
<%= link_to "Add Kitten", new_kitten_path %>
<%= render @kittens %>

app/views/kittens/new.html.erb
<h1>Add kitten</h1>
<%= render 'kittens/form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<ul>
  <li>Cuteness: <%= @kitten.cuteness %></li>
  <li>Softness: <%= @kitten.softness %></li>
  <li>Age: <%= @kitten.age %></li>
</ul>
<%= link_to "Edit Kitten", edit_kitten_path %><br>
<%= form_for @kitten, html: {method: :delete} do |f| %>
  <%= f.submit "Delete kitten" %>
<% end %>

<%= link_to "Back to index", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash.each { |label, msg| puts msg } %>
<%= yield %>

</body>
</html>